/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaCallC */

#ifndef _Included_JavaCallC
#define _Included_JavaCallC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaCallC
 * Method:    cMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaCallC_cMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
